export enum YandexTrackerToolName {
  getIssue = "getIssueTool",
  getMySelf = "getMySelfTool",
  getQueues = "getQueuesTool",
  getUser = "getUserTool",
  searchIssueByFilter = "searchIssueByFilterTool",
  searchIssueByQuery = "searchIssueByQueryTool",
  getIssueTypes = "getIssueTypesTool",
  getIssuePriorityTypes = "getIssuePriorityTypesTool",
  getIssueStatusTypes = "getIssueStatusTypesTool",
  getQueueFields = "getQueueFieldsTool",
  getUserFields = "getUserFieldsTool",
  getUsers = "getTrackerUsersTool",
  getYandexQueryDoc = "getYandexQueryDocTool",
  getBoards = "getBoardsTool",
  getBoardSprints = "getBoardSprintsTool",
  getSprint = "getSprintTool",
  getIssueComments = "getIssueCommentsTool",
  getIssueCheckList = "getIssueCheckListTool",
  getIssueChangeLog = "getIssueChangeLogTool",
  getIssueTransitions = "getIssueTransitions",
  getIssueFields = "getIssueFieldsTool",
}