@startuml b
left to right direction

actor "Продакт-менеджер" as PM

usecase "Сформировать рекомендации по составу минимально жизнеспособного продукта" as UC1
usecase "Получить рекомендации по приоритизации отложенных задач" as UC2
usecase "Получить анализ рисков для элементов списка отложенных задач" as UC3
usecase "Автоматически сформировать отчет о выполнении этапов проекта" as UC4
usecase "Взаимодействие через естественный язык" as UC5

PM -- UC5
UC1 ..> UC5
UC2 ..> UC5
UC3 ..> UC5
UC4 ..> UC5

@enduml