@startuml a
left to right direction

actor "Руководитель проекта" as PM


usecase "Получить рекомендации по оптимальному составу команды" as UC1
usecase "Получить сводку по текущим рискам проекта" as UC2
usecase "Получить рекомендации по приоритизации задач" as UC3
usecase "Получить прогноз трудозатрат" as UC4
usecase "Получить аналитический отчет по проекту" as UC5
usecase "Взаимодействие через естественный язык" as UC6


PM -- UC6
UC1 .> UC6
UC2 .> UC6
UC3 .> UC6
UC4 .> UC6
UC5 .> UC6

@enduml